config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'groups#index'
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  validates :name, presence: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :content, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, {:user_ids => []})
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group
  before_action :set_members

  def index
    @message = Message.new
   # @members = @group.users
    @messages = @group.messages.includes(:user)

    respond_to do |format|
      format.html
      format.json { @new_message = @group.messages.where('id > ?', params[:lastID]).includes(:user) }
    end
  end

  def create
    @message = @group.messages.new(message_params)
    respond_to do |format|
      if @message.save
        format.html { redirect_to group_messages_path(@group), notice: 'メッセージが送信されました' }
        format.json
      else
        format.html { @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
        render :index}
      end
    end
  end

  private
  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_members
    @members = set_group.users
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE(?)', "%#{params[:name]}%").where.not(id: current_user.id)
    respond_to do |format|
      format.json
      format.html { redirect_to root_path }
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def simple_time(time)
    time.strftime("%Y-%m-%d　%H:%M　")
  end
end

app/views/groups/_form.html.haml
= form_for group, html: {class: 'new_chat_group', id: 'new_chat_group'} do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
      - group.errors.full_messages.each do |message|
        %li= message
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, "グループ名", class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat_group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{type: 'text', placeholder: "追加したいユーザー名を入力してください"}
        #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      #chat-group-users
        = render partial: "user", collection: group.users
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit 'Save', class: 'chat-group-form__action-btn'

app/views/groups/_user.html.haml
.chat-group-user.clearfix{id: "group-user-#{user.id}"}
  %input{ type: "hidden", name: "group[user_ids][]", value: user.id}
  %p.chat-group-user__name= user.name
  - unless user.id == current_user.id
    %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn{'data-user-id': user.id} 削除

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
= render partial: 'shared/side_bar'

/ .chat-main
/   .header
/     .header-group
/       .header-group__name sampleグループ
/       = link_to "Edit", '#', class: "header-group__edit-btn"
/     .header-group-members
/       MEMBER:
/       %i Sample_User
/   .main
/     .main__message-list
/       .main__message
/         .main__message__name Sample_User
/         .main__message__time 2019/01/15 12:00:00
/         .main__message__text テストメッセージ
/   .main__footer
/     %form.main__footer-form
/       .main__footer-body
/         %input.message{type: "text", placeholder: "type a message", name: "message[body]"}
/         %label.chat-file{for: "message_image"}
/           %input.image{type: "file", id: "message_image", name: "message[image]"}
/           %i.fa.fa-picture-o
/       %input.submit{type: "submit", value: "Send"}

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body{"data-turbolinks": "false"}
    -# フラッシュメッセージの表示
    = render partial: 'layouts/flash'
    = yield

app/views/messages/_message.html.haml
.main__message{"data-id": "#{message.id}"}
  .main__message__name= message.user.name
  .main__message__time= message.created_at.to_s
- if message.content.present?
  .main__message__text= message.content
- if message.image.present?
  .main__message__image= image_tag message.image.url

app/views/messages/index.html.haml
= render partial: 'shared/side_bar'

.chat-main
  .header
    .header-group
      .header-group__name= @group.name
      = link_to "Edit", edit_group_path(params[:group_id]), class: "header-group__edit-btn"
    .header-group-members
      MEMBER:
      - @members.each do |member|
        %i #{member.name}
  .main
    .main__message-list
      = render partial: 'message', collection: @messages

      / .main__message
      /   .main__message__name Sample_User
      /   .main__message__time 2019/01/15 12:00:00
      /   .main__message__text テストメッセージ
      / .main__message
      /   .main__message__name Sample_User
      /   .main__message__time 2019/01/15 12:00:00
      /   .main__message__text テストメッセージ
      / .main__message
      /   .main__message__name Sample_User
      /   .main__message__time 2019/01/15 12:00:00
      /   .main__message__text テストメッセージ
      / .main__message
      /   .main__message__name Sample_User
      /   .main__message__time 2019/01/15 12:00:00
      /   .main__message__text テストメッセージ
  .main__footer
    = form_for [@group, @message], html: {class: "main__footer-form"} do |f|
      .main__footer-body
        = f.text_field :content, placeholder: "type a message", class: "message"
        = f.label :image, class: "chat-file" do
          = f.file_field :image
          %i.fa.fa-picture-o
      = f.submit "Send", class: "submit"

    / %form.main__footer-form
    /   .main__footer-body
    /     %input.message{type: "text", placeholder: "type a message", name: "message[body]"}
    /     %label.chat-file{for: "message_image"}
    /       %input.image{type: "file", id: "message_image", name: "message[image]"}
    /       %i.fa.fa-picture-o
    /   %input.submit{type: "submit", value: "Send"}

app/views/shared/_side_bar.html.haml
.sidebar
  .user
    %h1.user__name
      = current_user.name
    .user__icons
      = link_to new_group_path, class: "edit" do
        %i.fa.fa-edit
      = link_to edit_user_path(current_user), class: "cog" do
        %i.fa.fa-cog
  - current_user.groups.each do |group|
    = link_to group_messages_path(group) do
      .group
        %h2.group__name= group.name
        %p.group__new= group.show_last_message

  / .group
  /   %h2.group__name サンプル2
  /   %p.group__new テストテスト
  / .group
  /   %h2.group__name sampleグループ
  /   %p.group__new まだメッセージはありません

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'